### ISSUE TITLE
Palm and foot controler does'nt work.

### ISSUE THREAD

**Issue by d-j-a-y** [morevnaproject/characters#1]
Palm and foot controllers does'nt work. Moving the controllers does'nt change the shapes

synfig (1.0.2)

**Comment by morevnaproject** [comment]
Aha, I see. This is because hands and foots re animated using Z-Depth. This makes them affected by bug #868 - http://www.synfig.org/issues/thebuggenie/synfig/issues/868

**Comment by morevnaproject** [comment]
Fixed by removing Z-Depth animation (workaround).
